spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Sa123654!
    url: jdbc:mysql://192.168.20.12:3306/ysp_test?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  cloud:
    refresh:
      refreshable: none
  rabbitmq:
    host: 192.168.186.133
    port: 5672
    username: guest
    password: guest
boy:
  name: boom

  
